/*Copyright (c) 2017-2018 auditorius.ru All Rights Reserved.
 This software is the confidential and proprietary information of auditorius.ru You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with auditorius.ru*/

package com.repo_1native_ss_prototype.fn_service_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;

@Service
public class FN_Service_dbQueryExecutorServiceImpl implements FN_Service_dbQueryExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(FN_Service_dbQueryExecutorServiceImpl.class);

    @Autowired
    @Qualifier("FN_Service_dbWMQueryExecutor")
    private WMQueryExecutor queryExecutor;


}


