/*Copyright (c) 2017-2018 auditorius.ru All Rights Reserved.
 This software is the confidential and proprietary information of auditorius.ru You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with auditorius.ru*/
package com.repo_1native_ss_prototype.fn_service_db.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigInteger;
import java.sql.Date;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class StatsByDaysResponse implements Serializable {

    @ColumnAlias("date")
    private Date date;
    @ColumnAlias("sum(summ)")
    private Double sum_summ_;
    @ColumnAlias("sum(impressions)")
    private BigInteger sum_impressions_;
    @ColumnAlias("sum(clicks)")
    private BigInteger sum_clicks_;

    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public Double getSum_summ_() {
        return this.sum_summ_;
    }

    public void setSum_summ_(Double sum_summ_) {
        this.sum_summ_ = sum_summ_;
    }

    public BigInteger getSum_impressions_() {
        return this.sum_impressions_;
    }

    public void setSum_impressions_(BigInteger sum_impressions_) {
        this.sum_impressions_ = sum_impressions_;
    }

    public BigInteger getSum_clicks_() {
        return this.sum_clicks_;
    }

    public void setSum_clicks_(BigInteger sum_clicks_) {
        this.sum_clicks_ = sum_clicks_;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof StatsByDaysResponse)) return false;
        final StatsByDaysResponse statsByDaysResponse = (StatsByDaysResponse) o;
        return Objects.equals(getDate(), statsByDaysResponse.getDate()) &&
                Objects.equals(getSum_summ_(), statsByDaysResponse.getSum_summ_()) &&
                Objects.equals(getSum_impressions_(), statsByDaysResponse.getSum_impressions_()) &&
                Objects.equals(getSum_clicks_(), statsByDaysResponse.getSum_clicks_());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getDate(),
                getSum_summ_(),
                getSum_impressions_(),
                getSum_clicks_());
    }
}
