/*Copyright (c) 2017-2018 auditorius.ru All Rights Reserved.
 This software is the confidential and proprietary information of auditorius.ru You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with auditorius.ru*/
package com.repo_1native_ss_prototype.fn_service_db.dao;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.orm.hibernate4.HibernateTemplate;
import org.springframework.stereotype.Repository;

import com.wavemaker.runtime.data.dao.WMGenericDaoImpl;

import com.repo_1native_ss_prototype.fn_service_db.DeviceDictionary;

/**
 * Specifies methods used to obtain and modify DeviceDictionary related information
 * which is stored in the database.
 */
@Repository("FN_Service_db.DeviceDictionaryDao")
public class DeviceDictionaryDao extends WMGenericDaoImpl<DeviceDictionary, Integer> {

    @Autowired
    @Qualifier("FN_Service_dbTemplate")
    private HibernateTemplate template;

    public HibernateTemplate getTemplate() {
        return this.template;
    }
}

